require("mason").setup()
require("mason-lspconfig").setup()

local nvim_lsp = require("lspconfig")

nvim_lsp.tsserver.setup(require("martuico.plugins.lsp.ts"))
nvim_lsp.gopls.setup(require("martuico.plugins.lsp.go"))
nvim_lsp.intelephense.setup(require("martuico.plugins.lsp.php"))
--nvim_lsp.psalm.setup({})
--nvim_lsp.phpactor.setup({})
--nvim_lsp.cssls.setup(require("martuico.plugins.lsp.css"))
nvim_lsp.tailwindcss.setup(require("martuico.plugins.lsp.tailwind"))
--nvim_lsp.svelte.setup({})
nvim_lsp.rust_analyzer.setup(require("martuico.plugins.lsp.rust"))
nvim_lsp.diagnosticls.setup(require("martuico.plugins.lsp.diagnotics"))
--nvim_lsp.sumneko_lua.setup({})
